### ISSUE TITLE
This is not your code

### ISSUE THREAD

**Issue by Rahuletto** [WrightModzz/Calculator.djs#1]
Hello ! Rahuletto here, The owner of simply-djs, the whole package code has been stolen (copypasted) from my package/GitHub repository. I want you to Takedown this package (or) make the code yourselves. If I mean code yourselves I mean delete the file and make your own !

Thanks in regards. Rahul

Hope you respond fast

**Comment by Rahuletto** [comment]
I have proof too

https://media.discordapp.net/attachments/873539832155090944/908179760767705120/IMG_20211111_075141.jpg

**Comment by Rahuletto** [comment]
Where did nqn come from

https://media.discordapp.net/attachments/873539832155090944/908180177723482112/unknown.jpeg

**Comment by WrightModzz** [comment]
Will do, I thought I added credits in the readme.md file but I apparently didnt 🤣 , I just was wanting to make it an individual package with credits but apperently didn't, will take this package down and sorry for not contacting you to ask for permission

@Rahuletto
